### ISSUE TITLE
Login requires an email link every time

### ISSUE THREAD

**Issue by cfjedimaster** [brave/publishers#72]
Whenever I return to my publisher portal and select the option for a verified publisher, I have to request a new email link. Shouldn't it let me login w/o requesting an email every time?

**Comment by ayumi** [comment]
@cfjedimaster we made this change recently to improve security (see #51) in case login links are compromised. a possible alternative is optional user accounts (username and password), but we've avoided that thus far because we feel people generally have too many passwords to remember.

what would you prefer?

**Comment by cfjedimaster** [comment]
While I think you're right about too many logins, it really does seem a bit weird to *not* have one for this. It pretty much makes me want to *not* login because I know I'll have to wait for an email to show up. I'd add a proper login system. (Maybe just force Google/FB/Twitter/GitHub login so you can offload the auth.)

**Comment by ayumi** [comment]
thanks, that's helpful. I like the idea of using external identity providers and created #73 to track that.

**Comment by alexwykoff** [comment]
closing in favor of : https://github.com/brave/publishers/issues/64
